### PR TITLE
Release of v2.13.1 Docker images

### PR DESCRIPTION
**Pull request by mihaj**
@yjy44 I am trying to build Agens Graph images for version 2.13.1. I've changed the Dockerfile for alpine Linux, and when I run it, I get `': No such file or directory`. It looks like an issue with the `docker-entrypoint.sh` as I tried to build the `v2.13.0`, and I got the same error.

I think we need instructions to build the image locally too.

Let me know if I can make other changes in the MR.

### CODE REVIEW

**Comment by yjy44** [comment]
We are preparing docker for AgensGraph v2.13.1. I think v2.13.1 will solve the problem then. This won't take long.

Apart from that, can I request a screenshot of the error? If there are any issues we haven't found, we believe that a screenshot will help us get to the problem faster.

We will write detailed guidelines if necessary.

Thank you for the report.

**Comment by mihaj** [comment]
Ok, great!

To reproduce my issue, you can:

1. Use my Dockerfile in this merge request and run `docker build -t agensgraph:v2.13.1 .` The Image is created without errors.
2. I run the container by `docker run --name agensgraph2131 -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e PGDATA=/var/lib/postgresql/data/pgdata -v c:/Apps/DockerVolumes/agensgraph2131:/var/lib/postgresql/data agensgraph:v2.13.1`
3. Immediately after startup, I get the error `': No such file or directory`
image

I hope this helps.

**Comment by yjy44** [comment]
Thank you for error screenshot.

We'll check this issue and fix.

**Comment by mihaj** [comment]
Hi @yjy44 any news on this? If you need me to test something I can try.

**Comment by yjy44** [comment]
Hello. Due to a business bottleneck, we are currently a bit late with new versions and bug tracking. I have confirmed the test-related content you posted. We will figure it out and respond accordingly.

Thank you for your interest in our products. We will quickly resolve the situation and resolve this issue.

**Comment by yjy44** [comment]
Just to ask a question, can you share some info about that route as well? Looking at the simple error message, it only says it's a path problem, so I'd like to see the path information as well.

**Comment by mihaj** [comment]
> Just to ask a question, can you share some info about that route as well? Looking at the simple error message, it only says it's a path problem, so I'd like to see the path information as well.

I am not sure, somewhere in the `docker-entrypoint.sh` file. Maybe the docker build context is not OK?

**Comment by yjy44** [comment]
I merged but something was wrong about docker-entrypoint.sh.

Setting of that file is same to previous version, maybe I have to check why it failed.

**Comment by yjy44** [comment]
Maybe I found some problem.
Before additional commit, Can you test to local : chmod 777 to docker_entrypoint.sh at alpine?
After modify that auth , my local works well.

**Comment by mihaj** [comment]
Hmm, that does not work. I changed the ENTRYPOINT to:

```
ENTRYPOINT ["/bin/bash", "docker-entrypoint.sh"]
```

and changed the pipefail in the second line of `docker-entrypoint.sh`:

```
set -eo pipefail
```

The `-Eeo` is invalid for the bash.

And now it runs.

**Comment by mihaj** [comment]
Also, Debian and rocky suffer from the same issue.

**Comment by yjy44** [comment]
Well, would you like to PR that version?
I'll merge and test.

**Pull request merged**
